### PR TITLE
Add my script

### PR DESCRIPTION
**Pull request by osas2211**

### CODE REVIEW

**Comment by youthtrouble** [comment]
file extension is wrong, please review

**Comment by youthtrouble** [comment]
same problem, file extension

**Comment by osas2211** [comment]
> file extension is wrong, please review

alright,i have renamed it properly

**Comment by tomiwaajayi** [comment]
You are pushing the three files here.
Please make sure it is only one

**Comment by osas2211** [comment]
I really don't understand how to do this.

**Pull request closed without merging**
