### PR TITLE
Jxrry-HNG-00294 script

### PR DESCRIPTION
**Pull request by artoyebi**

### CODE REVIEW

**Comment by isongjosiah** [comment]
Hey artoyebi, a pull request from you has already been merged.

**Comment by artoyebi** [comment]
> 
> 
> Hey artoyebi, a pull request from you has already been merged.

I made a correction to it, that's why I made a new request.

**Comment by artoyebi** [comment]
Do I need to make another pull request since closed the last one I made?
Sorry for the inconveniences.

**Comment by isongjosiah** [comment]
No, i'll take care of it

**Pull request merged**
