### PR TITLE
Submissions

### PR DESCRIPTION
**Pull request by adedoyin89**

### CODE REVIEW

**Comment by sudo-kaizen** [comment]
You are to submit only one script. Delete one of your scripts

**Comment by adedoyin89** [comment]
Thank you. I've been trying to delete, but can't find the delete button.

**Comment by sudo-kaizen** [comment]
Delete it locally. Stage. Commit. Push and make a PR.
Welcome

**Comment by sudo-kaizen** [comment]
Also place the script in the scripts folder

**Comment by adedoyin89** [comment]
Done. Thank you.

**Pull request closed without merging**
