### PR TITLE
Updated my HNG code

### PR DESCRIPTION
**Pull request by phemmylintry**
Please, I just saw my HNG code has 3 zero's instead of two, though the script passed, I hope it won't affect me though

### CODE REVIEW

**Comment by youthtrouble** [comment]
please commit only one file

**Comment by phemmylintry** [comment]
I made changes to only one file now, I only made two commits, the first one was to update my fork repo from the master repo so that there won't be conflict and the second, I updated my file, So I made changes to only one file, Please check well

**Comment by youthtrouble** [comment]
Please reopen from your end

**Comment by phemmylintry** [comment]
I have another pr, I can't re-open this one

**Pull request closed without merging**
